$('.owl-carousel').owlCarousel({
    loop:false,
    margin:10,
    mouseDrag:false,
    nav:false,
    dots:true,
    responsive:{
        0:{
            items:1
        },
        180:{
            items:2
        },
        360:{
            items:3
        },
        540:{
            items:4
        },
        720:{
            items:5
        },
        900:{
            items:6
        },
        1080:{
            items:7
        },
        1260:{
            items:8
        },
        1440:{
            items:9
        },
        1620:{
            items:10
        },
    }
})